{
    'name': 'Dreezel Coffee',
    'summary': 'Point of Sale and Inventory Management for Dreezel Coffee',
    'description': 'POS system with inventory and purchase management for Dreezel Coffee.',
    'sequence': -100,
    'author': 'K02 G08',
    'category': 'Point of Sale',
    'version': '1.0',
    'license': 'LGPL-3',
    'depends': ['base', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/initial_data.xml',
        'views/category_views.xml',
        'views/ingredient_views.xml',
        'views/vendor_views.xml',
        'views/product_views.xml',
        'views/discount_views.xml',
        'views/transaction_views.xml',
        'views/purchase_order_views.xml',
        'views/notification_views.xml',
        'views/report_views.xml',
        'views/menus.xml',
    ],
    'demo': ['demo/demo.xml'],
    'assets': {
        'web.assets_backend': [
            'dreezel_coffee/static/src/js/create_label_patch.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
